openapi: 3.0.0
info:
  title: BUDA Editing API
  version: 0.0.1
servers:
- url: http://editserv.bdrc.io/
paths:
  /tasks/{taskId}:
    delete:
      parameters:
        - in: path
          name: taskId   # Note the name is the same as in the path
          required: true
          schema:
            type: string
            description: The task ID
            example: 2531329f-fb09-4ef7-887e-84e648214436
      description: delete the task given its id
      responses:
        '204':
          description: NO Content
    get:
      parameters:
        - in: path
          name: taskId   # Note the name is the same as in the path
          required: true
          schema:
            type: string
            description: The task ID
            example: 2531329f-fb09-4ef7-887e-84e648214436
      description: get the requested task given its id
      responses:
        '200':
          description: a task
          content:
            application/json:
              schema:
                description: task and sessions information (to be defined)
                example:
                  sessions:
                          - date: 1560282484000
                            gitVersion: commit 2102b42b069558725ede92e630f720b38a6e9893 1560282484 ----sp
                            taskVersion: '{"message":"about the task","id":"YYYYYY","shortName":"Yoga Collection","patch":"here is one more version of the content of the patch YYY","user":"marc","saveMsg":null}'
                          - date: 1560282368000
                            gitVersion: commit d12efc84bcc762f66bef09dcd32b577d78f5b9b4 1560282368 ----sp
                            taskVersion: '{"message":"about the task","id":"YYYYYY","shortName":"Yoga Collection","patch":"here is the latest ver sion of the content of the patch YYY","user":"marc","saveMsg":null}'
                          - date: 1559006942000
                            gitVersion: commit 659f85760596f8cff82acdcf0ffaa5fb85c54dbe 1559006942 ----sp
                            taskVersion: '{"message":"about the task","id":"YYYYYY","shortName":"Yoga Collection","patch":"here is the latest version of the content of the patch YYY","user":"marc","saveMsg":null}'
                  task:
                          message: about the task
                          id: YYYYYY
                          shortName: Yoga Collection
                          patch: here is one more version of the content of the patch YYY
                          user: marc
                          saveMsg: null
                        
                  
                  
  /tasks:
    put:    
      description: save or add an ongoing task of the current user for later edit
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              description: task information
              properties:
                id:
                  description: the unique identifier allows management of the task
                  type: string
                  example: 2531329f-fb09-4ef7-887e-84e648214436
                user:
                  description: identifier of the user
                  type: string
                  example: marc
                shortName:
                  description: a short name for the task
                  type: string
                  example: mdzöd bdun chinese titles
                message:
                  description: reminder message if wanted
                  type: string
                patch:
                  description: the patch being buit corresponding to the task
                  type: string
                  example: H  id     <uuid:1a2b3c4d-5e6f-7a8b-9c0d-e1f2a3b4c5r6> . H  graph  http://purl.bdrc.io/graph/P1524 . TX . A <http://purl.bdrc.io/resource/P1524> <http://purl.bdrc.io/ontology/core/personTeacherOf> <http://purl.bdrc.io/resource/P1583> <http://purl.bdrc.io/graph/P1524> . D <http://purl.bdrc.io/resource/P1524> <http://purl.bdrc.io/ontology/core/personTeacherOf> <http://purl.bdrc.io/resource/P1583> <http://purl.bdrc.io/graph/P1524>   . TC .
                saveMsg:
                  description: similar to a commit message
                  type: string
                  example: finished first volume titles
      responses:
        '204':
          description: NO Content 
          headers:
            Location:
              schema:
                type: string
                format: url
              description: URL of the newly added (or updated) task
    get:
      description: get the list of the tasks associated to the user
      responses:
        '200':
          description: list of tasks
          content:
            application/json:
              schema:
                description: task information
                properties:
                  id:
                    description: the unique identifier of the task
                    type: string
                    example: 2531329f-fb09-4ef7-887e-84e648214436
                  user:
                    description: identifier of the user
                    type: string
                    format: url
                    example: http://purl.bdrc.io/user/U0001
                  shortName:
                    description: a short name for the task
                    type: string
                    example: mdzöd bdun chinese titles
                  message:
                    description: reminder message if wanted
                    type: string
                  patch:
                    description: the patch being buit corresponding to the task
                    type: string
                  saveMsg:
                    description: similar to a commit message
                    type: string
                    example: finished first volume titles
    post:
      description: apply an existing task
      requestBody:
        description: the final version of a task
        required: true
        content:
          application/json:
            schema:
              description: task information
              properties:
                id:
                  description: the unique identifier allows management of the task
                  type: string
                  example: 2531329f-fb09-4ef7-887e-84e648214436
                user:
                  description: identifier of the user
                  type: string
                  format: url
                  example: http://purl.bdrc.io/user/U0001
                shortName:
                  description: a short name for the task
                  type: string
                  example: mdzöd bdun chinese titles
                message:
                  description: reminder message if wanted
                  type: string
                patch:
                  description: the patch to be applied,corresponding to the task
                  type: string
                saveMsg:
                  description: similar to a commit message
                  type: string
                  example: finished first volume titles
      responses:
        '200':
          description: task successfully submitted and queued
          headers:
            Location:
              schema:
                type: string
                format: url
              description: URL of the queued Job created for this task